import type { ThemePreset } from "../registry";

export const atelierThemePreset: ThemePreset = {
  key: "atelier",
  label: "Atelier",
  description: "Deep midnight, marble mist, and editorial serif typography inspired by the Digital Atelier system.",
  tokens: {
    canvas: "#F8F9FA",
    surface: "#FFFFFF",
    surfaceAlt: "#F3F4F5",
    surfaceStrong: "#E7E8E9",
    textPrimary: "#191C1D",
    textMuted: "#44474C",
    textInverse: "#FFFFFF",
    border: "#C5C6CC",
    borderStrong: "#75777C",
    primary: "#05101D",
    primaryForeground: "#FFFFFF",
    accent: "#4E6073",
    accentForeground: "#FFFFFF",
    success: "#2E7D32",
    successForeground: "#FFFFFF",
    danger: "#BA1A1A",
    dangerForeground: "#FFFFFF",
    navSolidBg: "#1A2533",
    navSolidFg: "#FFFFFF",
    navSolidInteractive: "#CFE2F9",
    focusRing: "#4E6073",
    shadowSoft: "0 32px 72px rgba(5, 16, 29, 0.06)",
  },
  components: {
    button: {
      primaryBg: "#05101D",
      primaryFg: "#FFFFFF",
      primaryHoverBg: "#1A2533",
      secondaryBg: "#F3F4F5",
      secondaryFg: "#05101D",
      secondaryHoverBg: "#E7E8E9",
      outlineBg: "#FFFFFF",
      outlineFg: "#05101D",
      outlineBorder: "#C5C6CC",
      outlineHoverBg: "#05101D",
      outlineHoverFg: "#FFFFFF",
      ghostFg: "#05101D",
      ghostHoverBg: "#F3F4F5",
      ghostHoverFg: "#05101D",
      destructiveBg: "#BA1A1A",
      destructiveFg: "#FFFFFF",
      destructiveHoverBg: "#93000A",
      linkFg: "#05101D",
      linkHoverFg: "#4E6073",
    },
  },
  typography: {
    headingFamily: "Noto Serif",
    bodyFamily: "Inter",
    headingFallback: "Georgia, serif",
    bodyFallback: "system-ui, sans-serif",
  },
  radius: {
    sm: "0.125rem",
    md: "0.25rem",
    lg: "0.5rem",
    pill: "0.75rem",
  },
};
